const Map<String, String> bnBD = {
  'login': 'লগইন',
  'username': 'ব্যবহারকারীর নাম',
  'password': 'পাসওয়ার্ড',
  'password_must': 'পাসওয়ার্ড *',
  'enter_password': 'পাসওয়ার্ড দিন',
  'date_of_birth': 'জন্ম তারিখ',
  'personal_id': 'ব্যক্তিগত আইডি *',
  'register': 'রেজিস্টার',
  'mobile_number': 'মোবাইল নম্বর *',
  'mobile_number_example': 'মোবাইল নম্বর উদাহরণ : ০১xxxxxxxxx',
  'email_example': 'ইমেল উদাহরণ : abc@example.com',
  'email': 'ইমেল (ঐচ্ছিক)',
  'register_account': 'একাউন্ট রেজিস্টার করুন',
  'information': 'তথ্য',
  'no_internet': 'ইন্টারনেট সংযোগ নেই।',
  'warning': 'সতর্কতা',
  'unknown_user': 'অপরিচিত ব্যবহারকারী',
  'login_alert': 'লগইন সতর্কতা!!!',
  'otp_verification': 'ওটিপি যাচাই',
  'click': 'অ্যাপয়েন্টমেন্টের জন্য ক্লিক করুন',
  'otp_limit': 'ওটিপি ৪ টি অক্ষর হতে হবে।',
  'enter_otp_error': '*অনুগ্রহ পূর্বক কোডটি প্রবেশ করুন',
  'verify': 'যাচাই করুন',
  'user_registration': 'ব্যবহারকারী নিবন্ধন',
  'enter_code_on_mobile': 'আপনার মোবাইল নম্বরে প্রেরিত কোড প্রবেশ করুন',
  'reg_successful': 'আপনার নিবন্ধন সফল হয়েছে। দয়া করে লগইন করুন।',
  'went_wrong': 'কিছু ভুল হয়েছে। দয়া করে আবার চেষ্টা করুন।',
  'required_data': 'দয়া করে সমস্ত প্রয়োজনীয় তথ্য পূরণ করুন।',
  'personal_id_example': 'ব্যক্তিগত আইডি উদাহরণ : BA-1234',
  'ok': 'ঠিক আছে',
  'no_room': 'কোন রুম পাওয়া যায়নি',
  'serial_number': 'আপনার সিরিয়াল নম্বর',
  'saved': 'সফলভাবে সংরক্ষিত হয়েছে',
  'new_appointment': 'নতুন অ্যাপয়েন্টমেন্ট',
  'select-paitient': 'রোগী সিলেক্ট করুন',
  'select-date': 'তারিখ সিলেক্ট করুন',
  'Select_department': 'ডিপার্টমেন্ট সিলেক্ট করুন',
  'select_time': 'সময় সিলেক্ট করুন',
  'select_periority': 'প্রাথমিকতা সিলেক্ট করুন',
  'chief_complaint': 'আপনার শারীরিক সমস্যা সম্পর্কিত তথ্য লিখুন',
  'submit': 'সাবমিট',
  'dr_appointment': 'ডাক্তারের অ্যাপয়েন্টমেন্ট',
  'no-data': 'কোন তথ্য পাওয়া যায়নি',
  'successful': 'সফলভাবে',
  'appoint_failed': 'ইতিমধ্যেই এই ডিপার্টমেন্টে অ্যাপয়েন্টমেন্ট নেওয়া হয়েছে',
  'canceled_appointment': 'আপনার অ্যাপয়েন্টমেন্ট বাতিল করা হয়েছে',
  'unable_cancel': 'এই মুহূর্তে অ্যাপয়েন্টমেন্ট বাতিল সম্ভব হয়নি ',
  'doctor_appointment': 'ডাক্তারের অ্যাপয়েন্টমেন্ট',
  'select_patient': 'ব্যবহারকারী সিলেক্ট করুন',
  'appointment_history': 'অ্যাপয়েন্টমেন্ট হিস্টরি',
  'appointment_no': 'অ্যাপয়েন্টমেন্ট নাম্বার',
  'serial_no': 'সিরিয়াল নাম্বার',
  'time': 'সময়',
  'dept': 'বিভাগ',
  'room': 'কক্ষ',
  'status': 'স্ট্যাটাস:',
  'active': 'সক্রিয়',
  'canceled': 'বাতিল',
  'cancel': 'বাতিল করুন',
  'doctors_appointment': 'ডাক্তারের\nঅ্যাপয়েন্টমেন্ট',
  'helth_recorsd': 'স্বাস্থ্য\nরেকর্ড',
  'bmi_calculator': 'বিএমআই\nক্যালকুলেটর',
  'blood_bank': 'রক্ত ব্যাংক',
  'health_tips': 'স্বাস্থ্য টিপস',
  'health_info': 'হাসপাতাল\nতথ্য',
  'telemedicine': 'টেলিমেডিসিন',
  'food_nu': 'খাবার ও\nপুষ্টি',
  'location': 'লোকেশন',
  'logout': 'লগআউট',
  'name': 'নাম : ',
  'user_profile': 'ব্যবহারকারীর প্রোফাইল',
  'more': 'আরও',
  'how_to_use': 'myCMH APP ব্যবহারবিধি',
  'current_version': 'বর্তমান সংস্করণ',
  'change_language': "ভাষা পরিবর্তন করুন",
  'app_size': 'অ্যাপ্লিকেশনের আকার',
  'permission_details': 'অনুমতি বিবরণী',
  'any_query': 'যদি কোনও প্রশ্ন থাকে',
  'qr_code': "BAR কোড",
  'logout_confirm': 'আপনি কি নিশ্চিত যে লগআউট করতে চান?',
  'no_appointment_found': 'কোন অ্যাপয়েন্টমেন্ট পাওয়া যায়নি',
  'select_patient_first': 'অনুগ্রহ করে ব্যবহারকারী সিলেক্ট করুন',
  'upcoming_feature': 'আপকামিং ফিচার',
  'lab_reports': 'নিয়মিত ও প্রয়োজনীয় টেস্টের রিপোর্ট',
  'email_at': 'আমাদের ইমেল করুন support@tilbd.net',
  'under_development': 'ফিচারটি সংযুক্ত করনের কাজ চলছে',
  'gender': 'Gender:',
  'email_address': 'Email:',
  'about': 'About',
  'user_id': 'ব্যবহারকারীর আইডি:',
  'joining_date': 'Joining date:',
  'date_of_birth_2': 'Date of Birth:',
  'password_change': 'পাসওয়ার্ড পরিবর্তন',
  'change_password': 'পাসওয়ার্ড পরিবর্তন করুন',
  'old_password': 'আগের পাসওয়ার্ড',
  'new_password': 'নতুন পাসওয়ার্ড',
  'forget_password': 'পাসওয়ার্ড ভুলে গেছেন?',
  'forget_password_text': 'পাসওয়ার্ড ভুলে গেছেন',
  'pass_change_successful': 'আপনার পাসওয়ার্ড সফলভাবে পরিবর্তন করা হয়েছে',
  'health_records': 'স্বাস্থ্য রেকর্ড',
  'prescription_no': 'প্রেসক্রিপশন নম্বর:',
  'date': 'তারিখ',
  'no_prescription_found': 'কোন প্রেসক্রিপশন পাওয়া যায়নি',
  'prescription': 'প্রেসক্রিপশন',
  'cancel_confirm': 'আপনি বাতিল করতে চান?',
  'feedback': 'সেবা \nসম্পর্কিত \nমতামত দিন',
  'reports': 'রিপোর্ট',
  'opd_reports': 'ল্যাব রিপোর্ট',
  'radiology_reports': 'রেডিওলজি রিপোর্ট',
  'submit_feedback': 'আপনার মূল্যবান মতামত দিন',
  'submit_feedback_hint': 'আপনার মতামত লিখুন (সর্বোচ্চ 100 শব্দ)',
  'no_report_found': 'কোনো রিপোর্ট পাওয়া যায়নি',
  'invoice_number': 'ইনভয়েচ নম্বর:',
  'report': 'রিপোর্ট',
  'date:': 'তারিখ:',
  'view_report': 'রিপোর্ট দেখুন',
  'food_nutrition': 'খাবার ও পুষ্টি',
  'telemedicine_title': 'টেলিমেডিসিন',
  'balanced_diet': 'সুষম খাদ্য',
  'balanced_diet_children': 'শিশুদের জন্য সুষম খাদ্য',
  'carcinoma_diet': 'কার্সিনোমা ডায়েট',
  'diabetic_diet': 'ডায়াবেটিক ডায়েট',
  'diabetic_renal_diet': 'ডায়াবেটিক রেনাল ডায়েট',
  'diarrheal_diet': 'ডায়রিয়া ডায়েট',
  'diet_chart_baby_1y': 'ডায়েট চার্ট (শিশু)-1y',
  'diet_chart_baby_2y': 'ডায়েট চার্ট (শিশু)-2y',
  'gallbladder_diet': 'গলব্লাডার ডায়েট',
  'high_fiber_diet': 'উচ্চ ফাইবার ডায়েট',
  'iron_rich_diet': 'আয়রন সমৃদ্ধ ডায়েট',
  'kids_diet_6m_8m.': 'বাচ্চাদের ডায়েট 6m-8m',
  'kids_diet_9m_12m.': 'বাচ্চাদের ডায়েট 9m-12m',
  'all_time': 'সার্বক্ষনিক',
  'telemedicine_desc':
      'স্বাস্থ্য সহায়তার জন্য "সেনা স্বাস্থ্যসেবা" নিম্ন মোবাইল নম্বরে যোগাযোগ করে সার্বক্ষণিক চিকিৎসকের কাছে আপনার সমস্যা জানিয়ে এসএমএস এর মাধ্যমে প্রেসক্রিপশন অনুযায়ী চিকিৎসা গ্রহন করুন',
  'remove_my_account': 'অ্যাকাউন্ট মুছে ফেলুন',
  'remove_my_account_details': 'আপনি কি নিশ্চিত?',
  'select_room': 'রুম নির্বাচন করুন',
  'empty_time_slot':
      'এই রুমের জন্য কোন টাইম স্লট নেই। অনুগ্রহ করে অন্য রুম নির্বাচন করুন।',
  "please_select_Patient": "অনুগ্রহ করে Patient নির্বাচন করুন",
  "please_select_date": "অনুগ্রহ করে তারিখ নির্বাচন করুন",
  "please_select_room": "অনুগ্রহ করে রুম নির্বাচন করুন",
  "please_select_department": "অনুগ্রহ করে Department নির্বাচন করুন",
  "please_select_time": "অনুগ্রহ করে অ্যাপয়েন্টমেন্ট সময় নির্বাচন করুন",
  'help_desk': 'সহায়তা \nডেস্ক',
  'help_desk_app_bar': 'সহায়তা ডেস্ক',
  'pay_bill': 'বিল পরিশোধ \nকরুন',
  'update_title': 'নতুন আপডেট',
  'update_now': 'এখনই আপডেট করুন',
  'create_appointment': 'অ্যাপয়েন্টমেন্ট করুন',
  'no_internet_connection': 'ইন্টারনেট সংযোগ নেই',
  'please_check_your_internet_connection':
      'অনুগ্রহ করে আপনার ইন্টারনেট সংযোগ যাচাই করুন এবং আবার চেষ্টা করুন।',
  'phone_number': 'ফোন নম্বর:',
  'rank': 'পদবী:',
  'server_error':
      'সাময়িক অসুবিধার জন্য দুঃখিত। অনুগ্রহ করে কিছুক্ষণ পর আবার চেষ্টা করুন।',
            'department_room': 'বিভাগ ও কক্ষ',
};
