const Map<String, String> enUS = {
  'login': 'Login',
  'username': 'Username',
  'password': 'Password',
  'password_must': 'Password *',
  'enter_password': 'Enter password',
  'date_of_birth': 'Date of Birth',
  'personal_id': 'Personal ID*',
  'register': 'Register',
  'mobile_number': 'Mobile number*',
  'mobile_number_example': 'Mobile number e.g : 01xxxxxxxxx',
  'email_example': 'Email e.g : abc@example.com',
  'email': 'Email',
  'register_account': 'Register Account',
  'information': 'Information',
  'no_internet': 'No Internet connection.',
  'warning': 'Warning',
  'unknown_user': 'Unauthorized user',
  'login_alert': 'Login Alert!!!',
  'otp_verification': 'OTP Verification',
  'otp_limit': 'OTP must be 4 characters.',
  'enter_otp_error': '*Please enter the code',
  'verify': 'VERIFY',
  'user_registration': 'User Registration',
  'enter_code_on_mobile': 'Enter the code sent to your mobile number',
  'reg_successful': 'Your registration is successful. Please login.',
  'pass_change_successful':
      'Your password has been successfully changed. Please login.',
  'went_wrong': 'Something went wrong. Please try again.',
  'required_data': 'Please fill up all required fields.',
  'personal_id_example': 'Personal id e.g : BA-1234',
  'ok': 'OK',
  'no_room': 'No Room found',
  'serial_number': 'Your serial number',
  'saved': 'Saved Successfully',
  'new_appointment': 'New Appointment',
  'select-paitient': 'Select Patient',
  'select-date': 'Select Date',
  'Select_department': 'Select Department',
  'select_time': 'Select Time',
  'select_periority': 'Select Priority',
  'chief_complaint': 'Enter Chief Complaint',
  'submit': 'Submit',
  'dr_appointment': 'Doctor Appointment',
  'no-data': 'No data found',
  'successful': 'Successful',
  'appoint_failed': 'Already taken appointment for this department',
  'canceled_appointment': 'Your appointment has been canceled.',
  'unable_cancel': 'Unable to cancel this appointment',
  'doctor_appointment': 'Doctor\'s Appointment',
  'select_patient': 'Select Patient',
  'appointment_history': 'Appointment History',
  'appointment_no': 'Appointment No',
  'serial_no': 'Serial No',
  'time': 'Time',
  'dept': 'Dept',
  'room': 'Room',
  'status': 'Status:',
  'active': 'Active',
  'canceled': 'Canceled',
  'cancel': 'Cancel',
  'click': 'Click for appointment',
  'doctors_appointment': "Doctor's\nAppointment",
  'helth_recorsd': "Health\nRecords",
  'bmi_calculator': "BMI\nCalculator",
  'blood_bank': "Blood Bank",
  'health_tips': "Health Tips",
  'health_info': "Hospital\nInfo",
  'telemedicine': "Tele\nMedicine",
  'food_nu': "Food &\nNutrition",
  'location': "Location",
  'logout': "Logout",
  'name': "Name : ",
  'user_profile': "User Profile",
  'more': "More",
  'change_language': "Change Language",
  'how_to_use': "How to use myCMH?",
  'current_version': "Current Version",
  'app_size': "App Size",
  'qr_code': "BAR Code",
  'permission_details': "Permission Details",
  'any_query': "For Any Query",
  'logout_confirm': "Are you sure to Logout??",
  'no_appointment_found': 'No Appointment Found',
  'select_patient_first': 'Please Select Patient',
  'upcoming_feature': 'Upcoming Feature',
  'lab_reports': 'Prescriptions & Lab Reports',
  'email_at': "Please email us at\nsupport@tilbd.net",
  'under_development': 'This feature currently under development',
  'gender': 'Gender:',
  'email_address': 'Email:',
  'about': 'About',
  'user_id': 'User ID:',
  'joining_date': 'Joining date:',
  'date_of_birth_2': 'Date of Birth:',
  'password_change': 'Password Change',
  'change_password': 'Change Password',
  'old_password': 'Old Password',
  'new_password': 'New Password',
  'forget_password': 'Forgot Password?',
  'forget_password_text': 'Forgot Password',
  'health_records': 'Health Records',
  'prescription_no': 'Prescription No:',
  'date': 'Date',
  'no_prescription_found': 'No Prescription Found',
  'prescription': 'Prescription',
  'cancel_confirm': 'Do you want to cancel?',
  'feedback': 'Feed back',
  'reports': 'Reports',
  'opd_reports': 'Lab Reports',
  'radiology_reports': 'Radiology Report',
  'submit_feedback': 'Submit Your Feedback',
  'submit_feedback_hint': 'Enter your feedback (max 100 words)',
  'no_report_found': 'No report found',
  'invoice_number': 'Invoice number:',
  'report': 'Report',
  'date:': 'Date:',
  'view_report': 'View Report',
  'food_nutrition': 'Food & Nutrition',
  'telemedicine_title': 'Telemedicine',
  'balanced_diet': 'Balanced Diet',
  'balanced_diet_children': 'Balanced Diet for children',
  'carcinoma_diet': 'Carcinoma Diet',
  'diabetic_diet': 'Diabetic Diet',
  'diabetic_renal_diet': 'Diabetic Renal Diet',
  'diarrheal_diet': 'Diarrheal Diet',
  'diet_chart_baby_1y': 'Diet chart (baby) -1y',
  'diet_chart_baby_2y': 'Diet chart (baby) -2y',
  'gallbladder_diet': 'Gallbladder Diet',
  'high_fiber_diet': 'High Fiber Diet',
  'iron_rich_diet': 'Iron Rich Diet',
  'kids_diet_2y_3y.': 'Kids Diet 2y-3y',
  'kids_diet_6m_8m.': 'Kids Diet 6 m -8 m',
  'kids_diet_9m_12m.': 'Kids Diet 9 m -12 m',
  'telemedicine_desc':
      'For health assistance call "Sena Health Care" on the following mobile number and report your problem to the doctor and receive treatment as per the prescription through SMS.',
  'all_time': 'All the time',
  'remove_my_account': 'Remove my account',
  'remove_my_account_details': 'Are you sure?',
  'select_room': 'Select Room',
  'empty_time_slot':
      'No available time slot for this room. Please select another room.',
  'please_select_Patient': 'Please Select Patient',
  'please_select_date': 'Please Select Date',
  'please_select_room': 'Please Select Room',
  'please_select_department': 'Please Select Department',
  'please_select_time': 'Please Select Appointment Time',
  'help_desk': 'Help Desk',
  'help_desk_app_bar': 'Help Desk',
  'pay_bill': 'Pay Bill',
  'update_title': 'Update Available',
  'update_now': 'Update Now',
  'create_appointment': 'Create Appointment',
  'no_internet_connection': 'No Internet Connection',
  'please_check_your_internet_connection':
      'Please check your internet connection and try again.',
  'phone_number': 'Mobile No.:',
  'rank': 'Rank:',
  'server_error':
      'Unable to process this request at the moment. Please try again later.',
      'department_room': 'Department & Room',
};
